server:
  port: 8080

spring:
  datasource:
    platform: postgresql
    url: jdbc:postgresql://localhost:5432/MusteriDB
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  security:
    user:
      name: admin
      password: root